# Pima Indians発症（糖尿病データセット）のロジスティック回帰モデルによる予測
#データセットをjupyterのhomeに置く
### UCIからダウンロード
https://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data
### Kaggleからダウンロード

https://www.kaggle.com/uciml/pima-indians-diabetes-database/version/1#_=_


# データを読み込む

In [1]:
import pandas as pd


filename = "pima-indians-diabetes.data.csv"
df = pd.read_csv(filename, sep=',',
                 header=True,
                 names=[
                     'Pregnancies',
                     'Glucose',
                     'Blood Pressure',
                     'Skin Thickness',
                     'Insulin',
                     'BMI',
                     'Diabetes Pedigree Function',
                     'Age',
                     'Outcome'
                 ]
                )
"""
# Kaggleからダウンロードした場合
filename="diabetes.csv"
df = pd.read_csv(filename, sep=',')
"""

df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

# 入力データとラベルデータを作成する

In [2]:

# pandas のデータフレームから入力データXとラベルデータYを作る
array = df.values
X = array[:,0:8]
Y = array[:,8]

# ノーマライズ（データの単位が異なるため）
from sklearn.preprocessing import normalize
X=normalize(X)

print("X.shape=",X.shape)
print("Y.shape=",Y.shape)

print("X=",X)
print("Y=",Y)


X.shape= (768, 8)
Y.shape= (768,)
X= [[0.03355237 0.82762513 0.40262844 ... 0.18789327 0.00350622 0.27960308]
 [0.008424   0.71604034 0.55598426 ... 0.22407851 0.00295683 0.26114412]
 [0.04039768 0.92409698 0.32318146 ... 0.11765825 0.00339341 0.16159073]
 ...
 [0.02691539 0.65135243 0.38758161 ... 0.14103664 0.00131885 0.16149234]
 [0.00665306 0.83828547 0.39918356 ... 0.20025708 0.00232192 0.31269379]
 [0.00791454 0.73605211 0.55401772 ... 0.24060198 0.00249308 0.18203439]]
Y= [1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0

# 学習と評価

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
import numpy as np
# 毎回異なる結果になるのを防ぐために、seed を固定する
np.random.seed(1234) 

# trainとtestに分ける
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y)

# モデルを定義する
model = LogisticRegression()

# モデルをトレーニングする
model.fit(X_train, Y_train)

# テストデータで評価する
accuracy=model.score(X_test,Y_test)

print("正答率=",accuracy)

正答率= 0.59375
